### ISSUE TITLE
???

### ISSUE THREAD

**Issue by erasin** [visualfc/goqt#2]
这里什么都没有

**Comment by cornfeedhobo** [comment]
+1

**Comment by ChingweiYu** [comment]
What?

2015-01-19 21:59 GMT+08:00 cornfeedhobo <notifications@github.com>:

**Comment by cornfeedhobo** [comment]
@ChingweiYu  there is nothing here

**Comment by JokerQyou** [comment]
An empty repo with 120+ stars? What is going on here?
