### ISSUE TITLE
failed to build the "minimal example"

### ISSUE THREAD

**Issue by roadev** [visualfc/goqt#27]
I'm getting this error on Archlinux:

```
go build: when using gccgo toolchain, please pass linker flags using -gccgoflags, not -ldflags
# github.com/visualfc/goqt/ui
/usr/bin/ld: cannot find -lqtdrv.ui
collect2: error: ld returned 1 exit status

```

**Comment by vendelin8** [comment]
Same for me on Debian.

**Comment by roadev** [comment]
I solved it just with copying libqtdrv.ui.so.1 to /usr/lib
```
cd bin
sudo cp libqtdrv.ui.so.1 /usr/lib
```

**Comment by roadev** [comment]
I solved it just with copying libqtdrv.ui.so.1 to /usr/lib
```
cd bin
sudo cp libqtdrv.ui.so.1 /usr/lib
```

**Comment by vendelin8** [comment]
I don't have a file named like this, and I wasn't able to find it. I tried google and apt-file search. Please, let me know, if you know it.

**Comment by roadev** [comment]
It is at bin directory (on your go-qt root folder)
That file is generated when you run the compile tasks at `ui` folder

![screenshot from 2016-04-07 18-58-57](https://cloud.githubusercontent.com/assets/4525107/14393318/e83af29c-fd8b-11e5-9262-4e8e6d09bd37.png)

**Comment by vendelin8** [comment]
Thanks, it worked. I think that "getting started" document is pretty much hidden, I'd put it in the main readme.

**Comment by roadev** [comment]
You're right :)
