### ISSUE TITLE
windows下面，第二步build qtdrv, need install QtSDK，出现错误

### ISSUE THREAD

**Issue by crazykun** [visualfc/goqt#5]
D:\Gopath\src\github.com\visualfc\goqt\qtdrv>mingw32-make
mingw32-make -f Makefile.Release
mingw32-make[1]: Entering directory 'D:/Gopath/src/github.com/visualfc/goqt/qtdrv'
g++ -Wl,-s -shared -Wl,-subsystem,windows -mthreads -Wl,--out-implib,D:/Gopath/src/github.com/visualfc/goqt/qtdrv/../bin/libqtdrv.ui.a -o ../bin/qtdrv.ui.dll object_script.qtdrv.ui.Release  -LC:/Qt/Qt5.5.1/5.5/mingw492_32/lib -lQt5UiTools -lQt5PrintSupport -lQt5Widgets -lQt5Gui -lQt5Core
./release/uiapplication.o: file not recognized: File format not recognized
collect2.exe: error: ld returned 1 exit status
Makefile.Release:110: recipe for target '../bin/qtdrv.ui.dll' failed
mingw32-make[1]: **\* [../bin/qtdrv.ui.dll] Error 1
mingw32-make[1]: Leaving directory 'D:/Gopath/src/github.com/visualfc/goqt/qtdrv'
makefile:34: recipe for target 'release' failed
mingw32-make: **\* [release] Error 2

qmake执行后，make过不去，总是出现错误，请问应该怎么办？

**Comment by visualfc** [comment]
看起来好象是mingw32版本与Qt5.5.1的mingw版本不一致。
也可以用QtCreator直接编译。

**Comment by visualfc** [comment]
mingw32-make clean
mingw32-make

也可以直接用QtCreator编译

**Comment by crazykun** [comment]
QtCreator附带的mingw32可以编译qtdrv和rcc 。
bin目录也看到了goqt_rcc.exe，libqtdrv.ui.a， qtdrv.ui.dll三个文件，但是到第四步build ui的时候，会提示 
ccl.exe：sorry ，unimplemented:64-bit mode not compiled in
下载64位的后，例子生成的exe点了没反应，请问应该怎么办？

**Comment by visualfc** [comment]
32位qt+32位go
64位qt+64位go
不可混用

**Comment by crazykun** [comment]
Qt官网minGw只有一个32位的
Qt 5.5.1 for Windows 32-bit (MinGW 4.9.2, 1.0 GB)    (info)

**Comment by visualfc** [comment]
GOARCH=386

**Comment by llxwj** [comment]
我在Windows7 64bit下,编译通过,例子也可以运行, 用的是qt4.8.6 mingw 4.9.2 golang1.5.2 32bit. 但是到Windows10 64bit下 qtdrv\ui 执行 go install -v的时候,就死了.等会把log贴上来.
